name:                ursus-maritimus
version:             0.1.0.0
github:              "sagifogel/ursus-maritimus"
license:             BSD3
author:              "Sagi Fogel"
maintainer:          "sagi.fogel@gmail.com"
copyright:           "2018 Sagi Fogel"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Haskell port of the scala ursus-martimus repo

dependencies:
- base >= 4.7 && < 5
- scotty
- yaml
- directory
- pipes
- pipes-concurrency
- dlist
- containers
- text
- mtl
- process-streaming
- bytestring
- exceptions
- pipes-safe
- process
- stm
- pipes-bytestring
- async

library:
  source-dirs: src

executables:
  ursus-maritimus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ursus-maritimus
    - scotty
    - yaml
    - directory
    - pipes
    - pipes-concurrency
    - dlist
    - containers
    - text
    - mtl
    - process-streaming
    - bytestring
    - exceptions
    - pipes-safe
    - process
    - stm
    - pipes-bytestring
    - async

tests:
  ursus-maritimus-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ursus-maritimus
    - scotty
    - yaml
    - pipes
    - pipes-concurrency
    - dlist
    - text
    - process-streaming